# Generated by Django 2.0.4 on 2018-05-08 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calculator', '0004_auto_20180508_1216'),
        ('importer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('data', models.ManyToManyField(to='calculator.ResultValueTime')),
                ('pair', models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='importer.Pair')),
            ],
        ),
    ]
