# Generated by Django 2.0.4 on 2018-05-11 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('importer', '0001_initial'),
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_choice', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell'), ('NONE', 'None')], default='None', max_length=2)),
                ('volume', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='RuleOn2Calculs',
            fields=[
                ('rule_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ruleManager.Rule')),
                ('action_choice', models.CharField(choices=[('GT', 'greater than'), ('GT', 'greater or equal than'), ('LT', 'lower than'), ('LT', 'lower or equal than'), ('NONE', 'None')], default='None', max_length=2)),
                ('data_1', models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='calculator.CalculOnTradeValue')),
            ],
            bases=('ruleManager.rule',),
        ),
        migrations.AddField(
            model_name='rule',
            name='pair',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='importer.Pair'),
        ),
        migrations.AddField(
            model_name='action',
            name='data_2',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='ruleManager.Rule'),
        ),
    ]
