# Generated by Django 2.0.4 on 2018-05-08 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruleManager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='data',
            field=models.ManyToManyField(to='calculator.Calcul'),
        ),
    ]
