# Generated by Django 2.0.4 on 2018-04-19 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.FloatField()),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='LastTrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valueLast', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Pair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Error', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ValeurTrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroechange', models.FloatField()),
                ('price', models.FloatField()),
                ('bs', models.CharField(default='Error', max_length=200)),
                ('ml', models.CharField(default='Error', max_length=200)),
                ('misce', models.CharField(default='Error', max_length=200)),
                ('time', models.DateTimeField()),
                ('pair', models.ForeignKey(default='Error', on_delete=django.db.models.deletion.CASCADE, to='importer.Pair')),
            ],
        ),
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Error', max_length=200)),
                ('pair', models.ForeignKey(default='Error', on_delete=django.db.models.deletion.CASCADE, to='importer.Pair')),
            ],
        ),
        migrations.AddField(
            model_name='lasttrade',
            name='pair',
            field=models.ForeignKey(default='Error', on_delete=django.db.models.deletion.CASCADE, to='importer.Pair'),
        ),
        migrations.AddField(
            model_name='data',
            name='value',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='importer.Value'),
        ),
    ]
