# Generated by Django 2.0.4 on 2018-04-23 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Error', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ValeurTrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.FloatField()),
                ('price', models.FloatField()),
                ('bs', models.CharField(default='', max_length=200)),
                ('ml', models.CharField(default='', max_length=200)),
                ('misce', models.CharField(default='', max_length=200)),
                ('time', models.DateTimeField(default=0)),
                ('pair', models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='importer.Pair')),
            ],
        ),
    ]
