# Generated by Django 2.0.4 on 2018-04-17 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0002_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='importer.Pair')),
            ],
        ),
        migrations.RemoveField(
            model_name='data',
            name='pair',
        ),
        migrations.AddField(
            model_name='data',
            name='data',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='data',
            name='value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='importer.Value'),
        ),
    ]
